lastupdatecheck: 0
recentrepos:
    - /mnt/c/Users/edgar/Documents/MainPP/hackrift2025-Clubit
startuppopupversion: 5
lastversion: 0.50.0
customcommandshistory:
    - q
    - echo hello
    - git config --global user.name "edgar"
    - submodule
hidecommandlog: true
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
