lastupdatecheck: 0
recentrepos:
    - /home/mcadmin/.dotfiles
startuppopupversion: 5
didshowhunkstaginghint: false
lastversion: 0.56.0
customcommandshistory:
    - q
    - echo hello
    - git config --global user.name "edgar"
    - submodule
hidecommandlog: true
